# frozen_string_literal: true

source 'https://rubygems.org'

gemspec

group :development do
  gem 'bundler', '>= 2.0'
  gem 'rake', '~> 13.4'
  gem 'rspec', '~> 3.13'
  gem 'rubocop', '~> 1.90'
  gem 'rubocop-rspec', '~> 3.10'
  gem 'yard', '~> 0.9'
  gem 'simplecov', '~> 0.22'
  gem 'simplecov-lcov', '~> 0.9'
end
