// Package main downloads the prebuilt pdf_oxide FFI library for the current
// platform from GitHub Releases and prints the CGO environment variables
// needed to build Go programs that depend on github.com/yfedoseev/pdf_oxide/go.
//
// Usage:
//
//	go run github.com/yfedoseev/pdf_oxide/go/cmd/install@v0.3.32
//
// Flags:
//
//	-version       Version to download (default: version baked in at build time)
//	-dir           Install directory (default: os.UserCacheDir()/pdf_oxide/v<ver>)
//	-shared        Download the shared library (.so/.dylib/.dll) for the
//	               purego backend (CGO_ENABLED=0) instead of the static .a
//	-write-flags   Directory to write a generated cgo_flags.go into
//	               (default: empty — just print env vars)
//	-env-only      Skip download; only print env vars for an existing install
//
// Design mirrors Kreuzberg's installer:
//
//	https://github.com/kreuzberg-dev/kreuzberg/blob/main/packages/go/v4/cmd/install/main.go
//
// Security posture: validates version format, constructs URL from a hard-coded
// base, enforces max-size on download + extraction, rejects path traversal.
package main

import (
	"archive/tar"
	"bytes"
	"compress/gzip"
	"crypto/sha256"
	"encoding/hex"
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"runtime"
	"runtime/debug"
	"strings"
	"text/template"
	"time"
)

const (
	// fallbackVersion is used only when `runtime/debug.ReadBuildInfo()` can't
	// report a real module version — i.e. `go run .` inside the checkout or
	// `go build` of the installer without a tagged module. In the normal
	// `go run github.com/.../cmd/install@<tag>` path, the module version is
	// taken from the build info and THIS constant is irrelevant. That's what
	// lets `@latest` just work — each tagged release resolves to its own
	// version automatically, without a sed step in release automation.
	fallbackVersion = "0.3.43"
	BaseURL         = "https://github.com/yfedoseev/pdf_oxide/releases/download"
	// cacheSubdir lives under os.UserCacheDir() — XDG_CACHE_HOME on Linux,
	// ~/Library/Caches on macOS (Time-Machine-excluded), %LocalAppData% on
	// Windows. Replaces the old $HOME/.pdf_oxide layout, which polluted
	// the home dir and didn't match platform conventions.
	cacheSubdir    = "pdf_oxide"
	dirPerm        = 0o750
	filePerm       = 0o644
	maxExtractSize = int64(500 * 1024 * 1024) // 500 MiB
	httpTimeout    = 5 * time.Minute
	osWindows      = "windows"
)

// defaultInstallRoot returns the per-user cache dir that should hold pdf_oxide
// native libs. Resolves to:
//
//	Linux:   $XDG_CACHE_HOME/pdf_oxide  or  ~/.cache/pdf_oxide
//	macOS:   ~/Library/Caches/pdf_oxide
//	Windows: %LocalAppData%\pdf_oxide
//
// Matches how Go's own toolchain picks GOCACHE.
func defaultInstallRoot() (string, error) {
	dir, err := os.UserCacheDir()
	if err != nil {
		return "", fmt.Errorf("resolve user cache dir: %w", err)
	}
	return filepath.Join(dir, cacheSubdir), nil
}

// resolveVersion returns the module version baked in by `go run ...@<tag>`.
// `debug.ReadBuildInfo()` reports Main.Version as "v0.3.32" for that path,
// "(devel)" for local builds inside the checkout, or "" when build info is
// missing entirely. We strip the leading "v" so the rest of the code can
// treat version as a plain semver string.
func resolveVersion() string {
	if info, ok := debug.ReadBuildInfo(); ok {
		v := info.Main.Version
		if v != "" && v != "(devel)" {
			return strings.TrimPrefix(v, "v")
		}
	}
	return fallbackVersion
}

// platformMapping maps "GOOS/GOARCH" to the release asset suffix we publish.
// Assets are named `pdf_oxide-go-ffi-<suffix>.tar.gz`.
var platformMapping = map[string]string{
	"linux/amd64":   "linux-amd64",
	"linux/arm64":   "linux-arm64",
	"darwin/amd64":  "darwin-amd64",
	"darwin/arm64":  "darwin-arm64",
	"windows/amd64": "windows-amd64",
}

// goDir maps "GOOS/GOARCH" to the GOOS_GOARCH directory name we extract into.
var goDir = map[string]string{
	"linux/amd64":   "linux_amd64",
	"linux/arm64":   "linux_arm64",
	"darwin/amd64":  "darwin_amd64",
	"darwin/arm64":  "darwin_arm64",
	"windows/amd64": "windows_amd64",
}

// Accepts `1.2.3` or `1.2.3-rc.1` — same shape the pdf_oxide release workflow uses.
var versionRegex = regexp.MustCompile(`^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9.]+)?$`)

// cgoFlagsTemplate generates a committed-per-machine cgo_flags.go with absolute
// paths from the install dir. Only emitted when --write-flags is passed.
const cgoFlagsTemplate = `// Code generated by pdf_oxide installer. DO NOT EDIT.
//go:build !pdf_oxide_dev

package pdfoxide

/*
#cgo CFLAGS: -I{{.IncludeDir}}
#cgo linux,amd64 LDFLAGS: {{.LinuxAmd64LDFLAGS}}
#cgo linux,arm64 LDFLAGS: {{.LinuxArm64LDFLAGS}}
#cgo darwin,amd64 LDFLAGS: {{.DarwinAmd64LDFLAGS}}
#cgo darwin,arm64 LDFLAGS: {{.DarwinArm64LDFLAGS}}
#cgo windows,amd64 LDFLAGS: {{.WindowsAmd64LDFLAGS}}
*/
import "C"
`

type cgoFlagsData struct {
	IncludeDir          string
	LinuxAmd64LDFLAGS   string
	LinuxArm64LDFLAGS   string
	DarwinAmd64LDFLAGS  string
	DarwinArm64LDFLAGS  string
	WindowsAmd64LDFLAGS string
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	version := flag.String("version", resolveVersion(), "Version to download (semver, e.g. 0.3.32). Defaults to the installer's own module version — so `go run ...@latest` and `go run ...@v0.3.32` both just work.")
	installDir := flag.String("dir", "", "Install directory (default: <user-cache-dir>/pdf_oxide/v<version>)")
	writeFlagsDir := flag.String("write-flags", "", "Directory in which to write cgo_flags.go (default: empty — just print env vars)")
	envOnly := flag.Bool("env-only", false, "Skip download; print env vars for an existing install")
	skipChecksum := flag.Bool("skip-checksum", false, "Skip SHA-256 checksum verification of the downloaded archive (NOT recommended)")
	shared := flag.Bool("shared", false, "Download the shared library (.so/.dylib/.dll) for the purego backend (CGO_ENABLED=0) instead of the static .a")
	flag.Parse()

	platform := runtime.GOOS + "/" + runtime.GOARCH
	assetSuffix, ok := platformMapping[platform]
	if !ok {
		supported := make([]string, 0, len(platformMapping))
		for p := range platformMapping {
			supported = append(supported, p)
		}
		return fmt.Errorf("unsupported platform %s (supported: %s)", platform, strings.Join(supported, ", "))
	}
	subdir, ok := goDir[platform]
	if !ok {
		return fmt.Errorf("no go-dir mapping for %s", platform)
	}

	targetDir := *installDir
	if targetDir == "" {
		root, err := defaultInstallRoot()
		if err != nil {
			return err
		}
		targetDir = filepath.Join(root, "v"+*version)
	}

	libDir := filepath.Join(targetDir, "lib", subdir)
	libFile := chosenLibName(platform, *shared)
	libPath := filepath.Join(libDir, libFile)
	includeDir := filepath.Join(targetDir, "include")

	if !*envOnly {
		if _, err := os.Stat(libPath); err == nil {
			fmt.Fprintf(os.Stderr, "pdf_oxide FFI already installed at %s\n", libPath)
		} else {
			if err := downloadAndExtract(*version, assetSuffix, targetDir, !*skipChecksum, *shared); err != nil {
				return err
			}
		}
	}

	if _, err := os.Stat(libPath); err != nil {
		return fmt.Errorf("library missing after install: %s", libPath)
	}

	if *writeFlagsDir != "" {
		if *shared {
			return fmt.Errorf("-write-flags is only meaningful for static (cgo) installs; purego reads PDF_OXIDE_LIB_PATH at runtime")
		}
		outPath, err := writeCgoFlagsGo(*writeFlagsDir, targetDir)
		if err != nil {
			return fmt.Errorf("write cgo_flags.go: %w", err)
		}
		fmt.Fprintf(os.Stderr, "Generated %s\n", outPath)
	}

	printEnv(libDir, includeDir, platform, *shared, libPath)
	return nil
}

// chosenLibName picks either the static archive or the platform-appropriate
// shared library file the caller asked for. The purego backend (CGO_ENABLED=0)
// only needs the shared lib; cgo needs the static .a.
func chosenLibName(platform string, shared bool) string {
	if !shared {
		return "libpdf_oxide.a"
	}
	switch platform {
	case "darwin/amd64", "darwin/arm64":
		return "libpdf_oxide.dylib"
	case "windows/amd64":
		return "pdf_oxide.dll"
	default:
		return "libpdf_oxide.so"
	}
}

func downloadAndExtract(version, assetSuffix, targetDir string, verifyChecksum, shared bool) error {
	if !versionRegex.MatchString(version) {
		return fmt.Errorf("invalid version %q (expected semver like 0.3.32)", version)
	}
	// Static (.a) ships under pdf_oxide-go-ffi-<platform>.tar.gz (pre-existing);
	// shared (.so/.dylib/.dll) under pdf_oxide-go-ffi-shared-<platform>.tar.gz.
	// Release workflow (stage 4) publishes both.
	variant := ""
	if shared {
		variant = "shared-"
	}
	assetName := "pdf_oxide-go-ffi-" + variant + assetSuffix + ".tar.gz"
	baseURL := BaseURL + "/v" + version + "/"
	url := baseURL + assetName
	fmt.Fprintf(os.Stderr, "Downloading %s\n", url)

	tgzBytes, err := httpGetLimited(url)
	if err != nil {
		return fmt.Errorf("download %s: %w", assetName, err)
	}

	if verifyChecksum {
		expected, err := fetchExpectedChecksum(baseURL + assetName + ".sha256")
		if err != nil {
			return fmt.Errorf("fetch checksum: %w\n(pass --skip-checksum to bypass)", err)
		}
		got := sha256.Sum256(tgzBytes)
		gotHex := hex.EncodeToString(got[:])
		if gotHex != expected {
			return fmt.Errorf("checksum mismatch for %s:\n  expected %s\n  got      %s", assetName, expected, gotHex)
		}
		fmt.Fprintf(os.Stderr, "sha256 ok (%s)\n", gotHex[:12])
	}

	if err := os.MkdirAll(targetDir, dirPerm); err != nil {
		return fmt.Errorf("mkdir %s: %w", targetDir, err)
	}
	if err := extractTarGz(bytes.NewReader(tgzBytes), targetDir); err != nil {
		return fmt.Errorf("extract: %w", err)
	}
	fmt.Fprintf(os.Stderr, "Installed to %s\n", targetDir)
	return nil
}

// httpGetLimited fetches a URL, enforces maxExtractSize*2 on body size, and
// returns the body as a byte slice. We buffer the whole asset in memory
// (max ~30 MB per platform) so we can hash it before extraction — it's
// simpler than a tee reader and safer than trusting a post-extraction
// signature check.
func httpGetLimited(url string) ([]byte, error) {
	client := &http.Client{Timeout: httpTimeout}
	resp, err := client.Get(url)
	if err != nil {
		return nil, fmt.Errorf("http get: %w", err)
	}
	defer func() {
		_, _ = io.Copy(io.Discard, resp.Body)
		_ = resp.Body.Close()
	}()

	switch resp.StatusCode {
	case http.StatusOK:
	case http.StatusNotFound:
		return nil, fmt.Errorf("HTTP 404 (asset not found): %s", url)
	default:
		return nil, fmt.Errorf("unexpected HTTP status %d for %s", resp.StatusCode, url)
	}
	if resp.ContentLength > 0 && resp.ContentLength > maxExtractSize*2 {
		return nil, fmt.Errorf("asset too large: %d bytes", resp.ContentLength)
	}

	// Read up to maxExtractSize*2 + 1 so we can detect overflow — a
	// chunked-encoded response reports no Content-Length, so the length
	// pre-check above is a no-op for chunked servers. If the body hits the
	// limit we can't distinguish "exactly the limit" from "more than the
	// limit"; erring on the side of rejection is safe because legitimate
	// FFI tarballs are well under the limit.
	limit := int64(maxExtractSize) * 2
	buf := new(bytes.Buffer)
	n, err := io.Copy(buf, io.LimitReader(resp.Body, limit+1))
	if err != nil {
		return nil, fmt.Errorf("read body: %w", err)
	}
	if n > limit {
		return nil, fmt.Errorf("asset too large: exceeded %d bytes", limit)
	}
	return buf.Bytes(), nil
}

// fetchExpectedChecksum downloads a `.sha256` file and returns the first
// 64-hex-char token it contains. Accepts either a plain hex digest or the
// shasum(1) format `<digest>  <filename>\n`.
func fetchExpectedChecksum(url string) (string, error) {
	body, err := httpGetLimited(url)
	if err != nil {
		return "", err
	}
	fields := strings.Fields(string(body))
	if len(fields) == 0 {
		return "", fmt.Errorf("empty checksum file at %s", url)
	}
	hash := strings.ToLower(fields[0])
	if len(hash) != 64 {
		return "", fmt.Errorf("unexpected checksum length %d (want 64 hex chars) at %s", len(hash), url)
	}
	for _, c := range hash {
		if !((c >= '0' && c <= '9') || (c >= 'a' && c <= 'f')) {
			return "", fmt.Errorf("non-hex character in checksum at %s", url)
		}
	}
	return hash, nil
}

func extractTarGz(r io.Reader, targetDir string) (retErr error) {
	gzr, err := gzip.NewReader(r)
	if err != nil {
		return fmt.Errorf("gzip reader: %w", err)
	}
	defer func() {
		if cerr := gzr.Close(); cerr != nil && retErr == nil {
			retErr = cerr
		}
	}()

	tr := tar.NewReader(gzr)
	for {
		hdr, err := tr.Next()
		if err == io.EOF {
			break
		}
		if err != nil {
			return fmt.Errorf("tar read: %w", err)
		}
		if hdr.Typeflag != tar.TypeReg {
			continue
		}
		// Assume archive layout: lib/<GOOS_GOARCH>/libpdf_oxide.a + include/pdf_oxide.h
		outPath := filepath.Join(targetDir, filepath.Clean(hdr.Name))
		if !isWithin(outPath, targetDir) {
			return fmt.Errorf("unsafe path in archive: %q", hdr.Name)
		}
		if err := os.MkdirAll(filepath.Dir(outPath), dirPerm); err != nil {
			return err
		}
		if err := writeFileLimited(tr, outPath, hdr.Size); err != nil {
			return err
		}
	}
	return nil
}

func writeFileLimited(src io.Reader, path string, size int64) (retErr error) {
	if size > maxExtractSize {
		return fmt.Errorf("file too large: %d bytes", size)
	}
	f, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, filePerm)
	if err != nil {
		return err
	}
	defer func() {
		if cerr := f.Close(); cerr != nil && retErr == nil {
			retErr = cerr
		}
	}()
	_, err = io.Copy(f, io.LimitReader(src, maxExtractSize))
	return err
}

func isWithin(target, base string) bool {
	rel, err := filepath.Rel(filepath.Clean(base), filepath.Clean(target))
	if err != nil {
		return false
	}
	return !strings.HasPrefix(rel, "..") && !filepath.IsAbs(rel)
}

// ldflagsFor returns the platform-specific static-link spec for a single
// platform, given its lib path. System-library lists come from
// `cargo rustc -- --print native-static-libs`.
func ldflagsFor(goos string, libPath string) string {
	switch goos {
	case "linux":
		return libPath + " -lm -lpthread -ldl -lrt -lgcc_s -lutil -lc"
	case "darwin":
		return libPath + " -framework CoreFoundation -framework Security -framework SystemConfiguration -liconv -lresolv"
	case osWindows:
		return libPath + " -lws2_32 -luserenv -lbcrypt -ladvapi32 -lcrypt32 -lsynchronization -lntdll -lkernel32 -lntoskrnl -lole32 -lshell32"
	default:
		return libPath
	}
}

func printEnv(libDir, includeDir, platform string, shared bool, libPath string) {
	goos := strings.Split(platform, "/")[0]

	if shared {
		// purego backend reads PDF_OXIDE_LIB_PATH at runtime; no CGO_* needed.
		fmt.Println("\n# Export to run Go programs with the pdf_oxide purego backend (CGO_ENABLED=0):")
		if goos == osWindows {
			fmt.Printf("set CGO_ENABLED=0\n")
			fmt.Printf("set PDF_OXIDE_LIB_PATH=%s\n", libPath)
		} else {
			fmt.Printf("export CGO_ENABLED=0\n")
			fmt.Printf("export PDF_OXIDE_LIB_PATH=%q\n", libPath)
		}
		return
	}

	ldflags := ldflagsFor(goos, libPath)
	cflags := "-I" + includeDir

	fmt.Println("\n# Export these to build Go programs that depend on pdf_oxide:")
	if goos == osWindows {
		fmt.Printf("set CGO_CFLAGS=%s\n", cflags)
		fmt.Printf("set CGO_LDFLAGS=%s\n", ldflags)
	} else {
		fmt.Printf("export CGO_CFLAGS=%q\n", cflags)
		fmt.Printf("export CGO_LDFLAGS=%q\n", ldflags)
	}
}

func writeCgoFlagsGo(outDir, installDir string) (string, error) {
	includeDir := filepath.Join(installDir, "include")
	libRoot := filepath.Join(installDir, "lib")
	data := cgoFlagsData{
		IncludeDir:          includeDir,
		LinuxAmd64LDFLAGS:   ldflagsFor("linux", filepath.Join(libRoot, "linux_amd64", "libpdf_oxide.a")),
		LinuxArm64LDFLAGS:   ldflagsFor("linux", filepath.Join(libRoot, "linux_arm64", "libpdf_oxide.a")),
		DarwinAmd64LDFLAGS:  ldflagsFor("darwin", filepath.Join(libRoot, "darwin_amd64", "libpdf_oxide.a")),
		DarwinArm64LDFLAGS:  ldflagsFor("darwin", filepath.Join(libRoot, "darwin_arm64", "libpdf_oxide.a")),
		WindowsAmd64LDFLAGS: ldflagsFor(osWindows, filepath.Join(libRoot, "windows_amd64", "libpdf_oxide.a")),
	}
	tmpl, err := template.New("cgo_flags").Parse(cgoFlagsTemplate)
	if err != nil {
		return "", err
	}
	outPath := filepath.Join(outDir, "cgo_flags.go")
	f, err := os.OpenFile(outPath, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, filePerm)
	if err != nil {
		return "", err
	}
	defer f.Close()
	if err := tmpl.Execute(f, data); err != nil {
		return "", err
	}
	return outPath, nil
}
